[build]
  publish = "."
  command = "" # no build needed since it's static

# Optional: if you want pretty URLs (no .html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


# Forward *all* API requests to Render
[[redirects]]
  from = "/api/*"
  to = "https://jnnai.onrender.com/:splat"
  status = 200
  force = true